# Generated by Django 5.0.1 on 2024-02-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_user_alter_order_user_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(max_length=70),
        ),
        migrations.AlterField(
            model_name='order',
            name='county',
            field=models.CharField(max_length=20),
        ),
    ]
